#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# Which carpentry is this ("swc", or "rsg")?
# swc: Software Carpentry, standard bash, python, git using the lessons from the Southampton-RSG-Training git-org
# rsg: Custom Lessons from the Southampton-RSG-Training git-org
carpentry: "rsg"

# Overall title for the Workshop.
# This variable is used to (optionally) add a title in the "jumbotron"
# (the grey box at the top of the page), and to the extra pages.
# Most workshops don't use extra pages. More information about extra
# pages are included in the README:
# https://github.com/carpentries/workshop-template#creating-extra-pages
title: "FIXME Workshop Title"

# Specify the location of the workshop
# TODO: needs documenting a lot better
venue: "FIXME"           # name of location
address: "FIXME"         # address of location
country: "FIXME"         # e.g. gb
language: "FIXME"        # e.g. en
latitude: "50.909698"    # latitude of location (Soton: 50.909698)
longitude: "-1.404351"   # longitude of location (Soton: -1.404351)

# Specify the start and end date of the workshop
humandate: "FIXME"      # e.g. "6th August"
humantime: "FIXME"      # e.g. "09:00-17:00"
startdate: FIXME        # e.g. YYYY-MM-DD
enddate: FIXME

# Specify the details of the instructors and helpers
# Can be list, or single string
instructor:
  - "Instructor 1"
  - "Instructor 2"
instructor-email:
  - "instructor1@domain.com"
  - "instructor2@domain.com"
helper:
  - "Helper 1"
  - "Helper 2"

# Details about the lessons
lessons:
  - title: Automating Tasks with the Unix Shell  # Lesson title
    gh-name: shell-novice                        # Name of the GitHub repository for the lesson at https://github:com/Southampton-RSG-Training:
    type: episode                                # Currently only 'episode' only is valid
    branch: gh-pages                             # Set the branch of the repository to use, useful for lesson customization
    date: 8 January 2022                         # The date of the lesson
    start-time: 10:30 am                         # The start time of the lesson

  - title: Version Control with git
    gh-name: git-novice
    type: episode
    branch: gh-pages
    date: 9 January 2022
    start-time: 8:30 am

#  - title: Building Programs with Python
#    gh-name: python-novice
#    type: episode
#    branch: gh-pages
#    date: 10 January 2022
#    start-time: 15:00

  - title: Managing Academic Software Development
    gh-name: project-novice
    type: episode
    branch: gh-pages
    date: 11 January 2022
    start-time: 8:30 am

#  - title: Best Practices in Data Organisation Using Spreadsheets
#    gh-name: spreadsheets
#    type: episode
#    branch: gh-pages
#    date: 12 January 2022
#    start-time: 16:00

#  - title: Data Cleaning with OpenRefine
#    gh-name: openrefine-data-cleaning
#    type: episode
#    branch: gh-pages
#    date: 13 January 2022
#    start-time: 15:00

#  - title: Data Analysis and Visualization in R
#    gh-name: r-novice
#    type: episode_r
#    branch: gh-pages
#    date: 14 January 2022
#    start-time: 15:00

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:slug
  extras:
    output: true
    permalink: /:path/index
collections_dir: collections

include:
  - _includes/rsg/

# If there is both an R and python official version of a curriculum
# (as listed on https://software-carpentry.org/lessons/ and
# https://datacarpentry.org/lessons/), change the
# value of the variable below ("flavor") to get the schedule and installation
# instructions updated accordingly (valid values are 'r' or 'python').
# Note: this is only for Data Carpentry and SWC at this time.
flavor: "python"

# If the workshop will be a lesson pilot (for a new official lesson or
# a lesson in The Carpentries Incubator), set pilot to "true".
pilot: false

#------------------------------------------------------------
# Incubator workshop settings (only relevant for workshops teaching a lesson
# in The Carpentries Incubator).
#
# For an Incubator workshop, uncomment the line below and add the URL of the lesson site.
# incubator_lesson_site: "put the URL of the lesson being taught here"
#
# For an Incubator workshop, uncomment the line below and add the URL of your pre-workshop survey
# incubator_pre_survey: "put the URL of your pre-workshop survey here"
#
# For an Incubator workshop, uncomment the line below and add the URL of your post-workshop survey
# incubator_post_survey: "put the URL of your post-workshop survey here"
#
#------------------------------------------------------------

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
# (Don't change this -- the contact address for your workshop will be set
# in the index.md file)
email: "team@carpentries.org"

# Using the new jekyll remote themes
remote_theme: carpentries/carpentries-theme

# Sites.
amy_site: "https://amy.carpentries.org/"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
incubator: "https://github.com/carpentries-incubator/"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
rsg_site: "https://rsgsoton.net"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Surveys.
pre_survey: "https://carpentries.typeform.com/to/wi32rS?slug="
post_survey: "https://carpentries.typeform.com/to/UgVdRQ?slug="

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page
#  - scope:
#      path: "fig"
#    values:
#      image: true


# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/
  - submodules/

# Turn on built-in syntax highlighting.
highlighter: rouge

plugins:
  - jekyll-sitemap
